const dmsData = {
  // Группы регионов
  regionGroups: [
    { id: 1, name: "Группа 1" },
    { id: 2, name: "Группа 2" },
    { id: 3, name: "Группа 3" },
    { id: 4, name: "Группа 4" },
    { id: 5, name: "Группа 5" },
    { id: 6, name: "Группа 6" },
    { id: 7, name: "Группа 7" },
    { id: 8, name: "Группа 8" },
  ],

  // Регионы (без districtId)
  regions: [
    { id: 1, name: "Москва", groupId: 1 },
    { id: 2, name: "Санкт-Петербург", groupId: 2 },
    { id: 3, name: "Алтайский край", groupId: 3 },
    { id: 4, name: "Архангельская область", groupId: 3 },
    { id: 5, name: "Астраханская область", groupId: 3 },
    { id: 6, name: "Брянская область", groupId: 3 },
    { id: 7, name: "Волгоградская область", groupId: 3 },
    { id: 8, name: "Вологодская область", groupId: 3 },
    { id: 9, name: "Воронежская область", groupId: 3 },
    { id: 10, name: "Еврейская автономная область", groupId: 3 },
    { id: 11, name: "Забайкальский край", groupId: 3 },
    { id: 12, name: "Кабардино-балкарская республика", groupId: 3 },
    { id: 13, name: "Карачаево-черкесская республика", groupId: 3 },
    { id: 14, name: "Кемеровская область", groupId: 3 },
    { id: 15, name: "Кировская область", groupId: 3 },
    { id: 16, name: "Курская область", groupId: 3 },
    { id: 17, name: "Липецкая область", groupId: 3 },
    { id: 18, name: "Магаданская область", groupId: 3 },
    { id: 19, name: "Ненецкий автономный округ", groupId: 3 },
    { id: 20, name: "Нижегородская область", groupId: 3 },
    { id: 21, name: "Орловская область", groupId: 3 },
    { id: 22, name: "Пензенская область", groupId: 3 },
    { id: 23, name: "Республика Адыгея (Адыгея)", groupId: 3 },
    { id: 24, name: "Республика Алтай", groupId: 3 },
    { id: 25, name: "Республика Бурятия", groupId: 3 },
    { id: 26, name: "Республика Ингушетия", groupId: 3 },
    { id: 27, name: "Республика Калмыкия", groupId: 3 },
    { id: 28, name: "Республика Марий Эл", groupId: 3 },
    { id: 29, name: "Республика Мордовия", groupId: 3 },
    { id: 30, name: "Республика Саха (Якутия)", groupId: 3 },
    { id: 31, name: "Республика Северная Осетия - Алания", groupId: 3 },
    { id: 32, name: "Республика Тыва", groupId: 3 },
    { id: 33, name: "Республика Хакасия", groupId: 3 },
    { id: 34, name: "Рязанская область", groupId: 3 },
    { id: 35, name: "Саратовская область", groupId: 3 },
    { id: 36, name: "Сахалинская область", groupId: 3 },
    { id: 37, name: "Смоленская область", groupId: 3 },
    { id: 38, name: "Тамбовская область", groupId: 3 },
    { id: 39, name: "Тверская область", groupId: 3 },
    { id: 40, name: "Тульская область", groupId: 3 },
    { id: 41, name: "Ульяновская область", groupId: 3 },
    { id: 42, name: "Ярославская область", groupId: 3 },
    { id: 43, name: "Ивановская область", groupId: 4 },
    { id: 44, name: "Костромская область", groupId: 4 },
    { id: 45, name: "Мурманская область", groupId: 4 },
    { id: 46, name: "Новгородская область", groupId: 4 },
    { id: 47, name: "Оренбургская область", groupId: 4 },
    { id: 48, name: "Пермский край", groupId: 4 },
    { id: 49, name: "Псковская область", groupId: 4 },
    { id: 50, name: "Республика Карелия", groupId: 4 },
    { id: 51, name: "Удмуртская Республика", groupId: 4 },
    { id: 52, name: "Чукотский автономный округ", groupId: 4 },
    { id: 53, name: "Амурская область", groupId: 5 },
    { id: 54, name: "Иркутская область", groupId: 5 },
    { id: 55, name: "Калининградская область", groupId: 5 },
    { id: 56, name: "Хабаровский край", groupId: 5 },
    { id: 57, name: "Челябинская область", groupId: 5 },
    { id: 58, name: "Белгородская область", groupId: 6 },
    { id: 59, name: "Калужская область", groupId: 6 },
    { id: 60, name: "Краснодарский край", groupId: 6 },
    { id: 61, name: "Красноярский край", groupId: 6 },
    { id: 62, name: "Новосибирская область", groupId: 6 },
    { id: 63, name: "Республика Дагестан", groupId: 6 },
    { id: 64, name: "Республика Коми", groupId: 6 },
    { id: 65, name: "Ростовская область", groupId: 6 },
    { id: 66, name: "Свердловская область", groupId: 6 },
    { id: 67, name: "Ставропольский край", groupId: 6 },
    { id: 68, name: "Чеченская республика", groupId: 6 },
    { id: 69, name: "Камчатский край", groupId: 7 },
    { id: 70, name: "Республика Башкортостан", groupId: 7 },
    { id: 71, name: "Тюменская область", groupId: 7 },
    { id: 72, name: "Ханты-Мансийский автономный округ", groupId: 7 },
    { id: 73, name: "Ямало-Ненецкий автономный округ", groupId: 7 },
    { id: 74, name: "Владимирская область", groupId: 8 },
    { id: 75, name: "Курганская область", groupId: 8 },
    { id: 76, name: "Омская область", groupId: 8 },
    { id: 77, name: "Приморский край", groupId: 8 },
    { id: 78, name: "Республика Татарстан (Татарстан)", groupId: 8 },
    { id: 79, name: "Самарская область", groupId: 8 },
    { id: 80, name: "Томская область", groupId: 8 },
    { id: 81, name: "Чувашская Республика - Чувашия", groupId: 8 },
  ],

  // Услуги
  services: [
    { id: "policlinika", name: "Поликлиника", required: true },
    {
      id: "stom_policlinika",
      name: "Стоматология на базе поликлиник + Специализированная стоматология",
      required: false,
    },
    {
      id: "spec_stom",
      name: "Специализированная стоматология",
      required: false,
    },
    { id: "pnd", name: "Помощь на дому", required: false },
    { id: "emergency", name: "Скорая медицинская помощь", required: false },
    {
      id: "eg",
      name: "Экстренная госпитализация",
      required: false,
    },
    {
      id: "eg_ep",
      name: "Экстренная и плановая госпитализация",
      required: false,
    },
  ],

  // Программы
  programs: [
    { id: "standard", name: "Стандарт", order: 1 },
    { id: "standard_plus", name: "Стандарт+", order: 2 },
    { id: "business", name: "Бизнес", order: 3 },
    { id: "vip", name: "ВИП", order: 4 },
    { id: "super_vip", name: "Супер ВИП", order: 5 },
  ],

  // Базовые тарифы по группам
  groupTariffs: {
    1: {
      policlinika: {
        standard: 23644,
        standard_plus: 32900,
        business: 51217,
        vip: 64153,
        super_vip: 290527,
      },
      stom_policlinika: {
        standard: 13610,
        standard_plus: 15000,
        business: 18178,
        vip: 21478,
        super_vip: 63423,
      },
      spec_stom: {
        standard: 11865,
        standard_plus: 13200,
        vip: 23308,
      },
      pnd: {
        standard: 1300,
        standard_plus: 1300,
        business: 1300,
        vip: 1300,
        super_vip: 1300,
      },
      emergency: {
        standard: 1700,
        standard_plus: 1700,
        business: 1700,
        vip: 1700,
        super_vip: 1700,
      },
      eg: {
        standard: 2200,
        standard_plus: 2880,
        business: 2880,
        vip: 3420,
        super_vip: 3420,
      },
      eg_ep: {
        standard: 2760,
        standard_plus: 3720,
        business: 3720,
        vip: 4380,
        super_vip: 4380,
      },
    },
    2: {
      policlinika: {
        standard: 15559,
        standard_plus: 22230,
        business: 36410,
        vip: 41209,
        super_vip: 56155,
      },
      stom_policlinika: {
        business: 11514,
        vip: 19890,
        super_vip: 32803,
      },
      spec_stom: {
        standard: 13050,
      },
      pnd: {
        standard: 1170,
        standard_plus: 1170,
        business: 1170,
        vip: 1170,
        super_vip: 1170,
      },
      emergency: {
        standard: 1170,
        standard_plus: 1170,
        business: 1170,
        vip: 1170,
        super_vip: 1170,
      },
      eg: {
        standard: 972,
        standard_plus: 2160,
        business: 2160,
        vip: 3078,
        super_vip: 3078,
      },
      eg_ep: {
        standard: 1458,
        standard_plus: 2970,
        business: 2970,
        vip: 4482,
        super_vip: 4482,
      },
    },
    3: {
      policlinika: {
        standard: 5665,
        standard_plus: 10311,
        business: 14163,
        vip: 22660,
        super_vip: 24401,
      },
      stom_policlinika: {
        standard: 5099,
        standard_plus: 9291,
        business: 12803,
        vip: 20394,
        super_vip: 21961,
      },
      pnd: {
        standard: 500,
        standard_plus: 1000,
        business: 1300,
        vip: 2000,
        super_vip: 2300,
      },
      eg: {
        standard: 1020,
        standard_plus: 1320,
        business: 1800,
        vip: 2220,
        super_vip: 3000,
      },
      eg_ep: {
        standard: 1740,
        standard_plus: 2220,
        business: 3060,
        vip: 3780,
        super_vip: 5040,
      },
    },
    4: {
      policlinika: {
        standard: 6572,
        standard_plus: 10311,
        business: 14163,
        vip: 22660,
        super_vip: 24401,
      },
      stom_policlinika: {
        standard: 6005,
        standard_plus: 9291,
        business: 12803,
        vip: 20394,
        super_vip: 21961,
      },
      pnd: {
        standard: 600,
        standard_plus: 1000,
        business: 1300,
        vip: 2000,
        super_vip: 2300,
      },
      eg: {
        standard: 1020,
        standard_plus: 1320,
        business: 1800,
        vip: 2220,
        super_vip: 3000,
      },
      eg_ep: {
        standard: 1740,
        standard_plus: 2220,
        business: 3060,
        vip: 3780,
        super_vip: 5040,
      },
    },
    5: {
      policlinika: {
        standard: 7592,
        standard_plus: 14163,
        business: 17902,
        vip: 29458,
        super_vip: 31721,
      },
      stom_policlinika: {
        standard: 6912,
        standard_plus: 12803,
        business: 16202,
        vip: 26513,
        super_vip: 28645,
      },
      pnd: {
        standard: 700,
        standard_plus: 1300,
        business: 1600,
        vip: 2600,
        super_vip: 3000,
      },
      eg: {
        standard: 1260,
        standard_plus: 1560,
        business: 2160,
        vip: 2700,
        super_vip: 3600,
      },
      eg_ep: {
        standard: 1740,
        standard_plus: 2220,
        business: 3060,
        vip: 3780,
        super_vip: 5040,
      },
    },
    6: {
      policlinika: {
        standard: 7592,
        standard_plus: 14163,
        business: 18922,
        vip: 29458,
        super_vip: 31721,
      },
      stom_policlinika: {
        standard: 6912,
        standard_plus: 12803,
        business: 17109,
        vip: 26513,
        super_vip: 28645,
      },
      pnd: {
        standard: 700,
        standard_plus: 1300,
        business: 1700,
        vip: 2600,
        super_vip: 3000,
      },
      eg: {
        standard: 1020,
        standard_plus: 1320,
        business: 1800,
        vip: 2220,
        super_vip: 3000,
      },
      eg_ep: {
        standard: 1740,
        standard_plus: 2220,
        business: 3060,
        vip: 3780,
        super_vip: 5040,
      },
    },

    7: {
      policlinika: {
        standard: 7592,
        standard_plus: 15069,
        business: 22660,
        vip: 32857,
        super_vip: 35435,
      },
      stom_policlinika: {
        standard: 6912,
        standard_plus: 13596,
        business: 20394,
        vip: 29572,
        super_vip: 31934,
      },
      pnd: {
        standard: 700,
        standard_plus: 1400,
        business: 2000,
        vip: 2900,
        super_vip: 3400,
      },
      eg: {
        standard: 1020,
        standard_plus: 1320,
        business: 1800,
        vip: 2220,
        super_vip: 3000,
      },
      eg_ep: {
        standard: 1740,
        standard_plus: 2220,
        business: 3060,
        vip: 3780,
        super_vip: 5040,
      },
    },
    8: {
      policlinika: {
        standard: 8498,
        standard_plus: 12237,
        business: 15296,
        vip: 28325,
        super_vip: 30554,
      },
      stom_policlinika: {
        standard: 7705,
        standard_plus: 11104,
        business: 13823,
        vip: 25493,
        super_vip: 27584,
      },
      pnd: {
        standard: 800,
        standard_plus: 1100,
        business: 1400,
        vip: 2500,
        super_vip: 2900,
      },
      eg: {
        standard: 1020,
        standard_plus: 1320,
        business: 1800,
        vip: 2220,
        super_vip: 3000,
      },
      eg_ep: {
        standard: 1740,
        standard_plus: 2220,
        business: 3060,
        vip: 3780,
        super_vip: 5040,
      },
    },
  },
};
